version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'